
CREATE DATABASE MARKETPLACE
use MARKETPLACE






CREATE TABLE TB_USUARIOS(
ID_Usuarios INT NOT NULL PRIMARY KEY,
Nome varchar(250) NOT NULL,
Usuario varchar(250) NOT NULL,
Senha varchar(250) NOT NULL,
CPF int NOT NULL,
);

CREATE TABLE TB_CARRINHO(
ID_Carrinho INT NOT NULL PRIMARY KEY,
Produtos varchar(250),
Preco FLOAT,

FK_Comprador INT NOT NULL,
FK_Produto INT NOT NULL,

FOREIGN KEY (FK_Comprador) REFERENCES TB_USUARIOS (ID_Usuarios),FOREIGN KEY (FK_Produto) REFERENCES TB_PRODUTO (ID_Produto)
);

CREATE TABLE TB_PRODUTO(
ID_Produto INT NOT NULL PRIMARY KEY,
Categoria varchar(250) NOT NULL,
Produto varchar(250) NOT NULL,
quantidade INT NOT NULL,
Valor float NOT NULL,
);


DROP TABLE TB_USUARIOS
DROP TABLE TB_CARRINHO
